services:
  - type: web
    name: naiyuan-backend
    env: node
    plan: free
    buildCommand: ./build.sh
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: naiyuan-db
          property: connectionString
